name: Build APK for Android 4.0+

on:
  # 支持手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检查代码库
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: 设置 JDK 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Step 3: 缓存 Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-

    # Step 4: 构建 APK
    - name: Build APK
      run: ./gradlew assembleRelease

    # Step 5: 保存 APK 文件为 Artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/*.apk
